apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: incidents-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: incidents-deployment-api
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120 #how long to wait before reevaluating and triggering a scaledown event
      policies:
        - type: Pods #You c. an scale based on pods, or percent
          value: 1
          periodSeconds: 35
    scaleUp:
      stabilizationWindowSeconds: 60 
      policies:
        - type: Pods
          value: 2
          periodSeconds: 35 # resource utilization metric must hold true for this long
        
      
