apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: incident-instrumentation
  namespace: chaz
spec:
  exporter:
    endpoint: http://tempo.monitoring:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  python:
    env:
      # Required if endpoint is set to 4317.
      # Python autoinstrumentation uses http/proto by default
      # so data must be sent to 4318 instead of 4137.
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://tempo.monitoring:4318
      - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
        value: 'http/protobuf'
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest
