---
apiVersion: v1
kind: Service
metadata:
  namespace: chaz
  name: incidents-front-service
spec:
  type: NodePort
  selector:
    app: incidents-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  namespace: chaz
  name: incidents-api-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics/"
    prometheus.io/host: "incidents-api.chaz.pro"
spec:
  type: NodePort
  selector:
    app: incidents-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000


---
apiVersion: v1
kind: Service
metadata:
  namespace: chaz
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: incidents-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
