apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: incidents
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chazapp/incidents-k8s
    targetRevision: HEAD
    path: ./kustomize/
  destination:
    server: https://kubernetes.default.svc
    namespace: chaz
  syncPolicy:
    automated: {}