---
apiVersion: v1
kind: Service
metadata:
  name: incidents-front-service
spec:
  type: NodePort
  selector:
    app: incidents-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
