{{ if .Values.api.enabled }}
---
kind: Secret
apiVersion: v1
metadata:
    name: incidents-api-secret
type: Opaque
stringData:
    SECRET_KEY: {{ .Values.api.config.secretKey }}
    DB_USER: {{ .Release.Name }}
    DB_PASSWORD: {{ .Values.api.config.dbPassword}}
    DB_NAME: {{ .Release.Name }}
    ADMIN_EMAIL: {{ .Values.api.config.adminEmail }}
    ADMIN_PASSWORD: {{ .Values.api.config.adminPassword }}
{{- end -}}