---
{{ if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
spec:
  selector:
    app: {{ .Release.Name }}-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
{{- end -}}

{{ if .Values.front.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-front
spec:
  selector:
    app: {{ .Release.Name }}-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

{{- end -}}