---
name: Checkov
on:
  push:

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          quiet: true
          
